# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Mohammed Saqib
email: saqibm128@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://saqibm128.github.io" # the base hostname & protocol for your site
twitter_username: saqibm128
github_username:  Saqibm128
description: >
    Computer Science and Biomedical Engineering Student at Georgia Tech completing final year of undergraduate study.
    Proficient in both machine learning and highly scalable web services. I am particularly interested in working in projects with an impact on the healthcare system.
# Build settings
markdown: kramdown
